import type { Question } from "./types";

export const demoQuestions: Question[] = [
  {
    id: "q1",
    number: "1",
    body: "Which blood vessel carries blood away from the heart?",
    marks: "2 / 2",
    score: 2,
    maxMarks: 2,
    status: "good",
    answered: true,
    page: 1,
    answerPage: 1,
    feedback: "Correct answer! Arteries carry oxygenated blood away from the heart at high pressure.",
    extractedAnswerText: "Arteries carry blood away from the heart. Photosynthesis is the process used by green plants to convert light energy into chemical energy.",
    region: { x: 2, y: 2, width: 95, height: 28, page: 1 },
  },
  {
    id: "q2",
    number: "2",
    body: "Which of the following organelles is primarily involved in photosynthesis?",
    marks: "2 / 2",
    score: 2,
    maxMarks: 2,
    status: "good",
    answered: true,
    page: 1,
    answerPage: 1,
    feedback: "Excellent work! You correctly identified the chloroplast as the organelle responsible for photosynthesis. Keep it up!",
    extractedAnswerText: "The process mainly occurs in the chloroplast of the plant cell. It has two main stages: 1. Light reaction — captures light energy. 2. Dark reaction — uses energy to make glucose.",
    region: { x: 2, y: 32, width: 95, height: 28, page: 1 },
  },
  {
    id: "q3",
    number: "3",
    body: "Explain the role of chloroplasts in photosynthesis, naming the main pigments involved and briefly outlining the two major stages of the process.",
    marks: "2 / 2",
    score: 2,
    maxMarks: 2,
    status: "good",
    answered: true,
    page: 1,
    answerPage: 1,
    feedback: "Well articulated. Chlorophyll pigments and light/dark reactions are accurately outlined.",
    extractedAnswerText: "Chloroplasts contain chlorophyll, which absorbs sunlight to make food for the plant.",
    region: { x: 2, y: 62, width: 95, height: 32, page: 1 },
  },
  {
    id: "q4",
    number: "4",
    body: "Describe the flow of blood through the human heart starting from the right atrium and ending at the aorta; include the names of valves crossed.",
    marks: "0 / 2",
    score: 0,
    maxMarks: 2,
    status: "missing",
    answered: false,
    page: 1,
    answerPage: 2,
    feedback: "This question was left unanswered by the student. No response was found on the answer sheet.",
    region: { x: 2, y: 5, width: 95, height: 18, page: 2 },
  },
  {
    id: "q5",
    number: "5",
    body: "Draw a labelled diagram of an alveolus showing capillaries and air space (label alveolar sac, capillary, and direction of gas exchange).",
    marks: "2 / 2",
    score: 2,
    maxMarks: 2,
    status: "good",
    answered: true,
    page: 1,
    answerPage: 2,
    feedback: "Accurate drawing with clear depiction of alveolar membrane, capillary network, and O₂/CO₂ diffusion arrows.",
    extractedAnswerText: "[Diagram of Alveolus showing capillary bed, thin epithelial lining, and gas diffusion arrows]",
    region: { x: 2, y: 26, width: 95, height: 34, page: 2 },
  },
  {
    id: "q6",
    number: "6",
    body: "Draw a neat labelled diagram of the human digestive system (stomach, small intestine, large intestine, liver, pancreas) and label the site where most absorption occurs.",
    marks: "4 / 5",
    score: 4,
    maxMarks: 5,
    status: "good",
    answered: true,
    page: 1,
    answerPage: 2,
    answerPages: [2, 3],
    feedback: "Very good diagram spanning onto Page 3. Site of absorption (small intestine/villi) labelled accurately. Deducted 1 mark for minor inaccuracy in pancreas positioning.",
    extractedAnswerText: "[Multi-page answer: Digestive tract diagram on Page 2 and continuation of gland labelling and absorption summary on Page 3]",
    region: { x: 2, y: 62, width: 95, height: 35, page: 2 },
  },
  {
    id: "q7",
    number: "7",
    body: "Draw and label a nephron (Bowman's capsule, glomerulus, proximal tubule, loop of Henle, distal tubule, collecting duct).",
    marks: "5 / 5",
    score: 5,
    maxMarks: 5,
    status: "good",
    answered: true,
    page: 2,
    answerPage: 3,
    feedback: "Complete and clear diagram with all six mandatory structural components correctly labelled.",
    extractedAnswerText: "[Detailed nephron diagram: Glomerulus in Bowman's capsule -> PCT -> Loop of Henle -> DCT -> Collecting duct]",
    region: { x: 2, y: 4, width: 95, height: 36, page: 3 },
  },
  {
    id: "q8",
    number: "8",
    body: "Explain the structural differences between palisade mesophyll and spongy mesophyll and state how each structure aids its function in the leaf.",
    marks: "3 / 5",
    score: 3,
    maxMarks: 5,
    status: "partial",
    answered: true,
    page: 2,
    answerPage: 3,
    feedback: "Answered out of sequence on Page 3. Good attempt detailing palisade cells tightly packed with chloroplasts. Spongy mesophyll air spaces and gas exchange function could be elaborated for full marks.",
    extractedAnswerText: "Palisade mesophyll cells are column-shaped and packed with chloroplasts for light absorption. Spongy mesophyll cells are loosely arranged with air spaces.",
    region: { x: 2, y: 42, width: 95, height: 26, page: 3 },
  },
  {
    id: "q9",
    number: "9",
    body: "Describe the process of transpiration in plants in two to three sentences and name two environmental factors that increase its rate.",
    marks: "5 / 5",
    score: 5,
    maxMarks: 5,
    status: "good",
    answered: true,
    page: 2,
    answerPage: 3,
    feedback: "Spot-on explanation of evaporation through stomata creating suction pull. Correctly cited temperature and wind speed as accelerating factors.",
    extractedAnswerText: "Transpiration is the loss of water vapour from plant leaves through stomata. It creates a transpiration pull. Factors: 1. Higher temperature, 2. Wind speed.",
    region: { x: 2, y: 70, width: 95, height: 26, page: 3 },
  },
  {
    id: "q10",
    number: "10",
    body: "Explain how the structure of xylem vessels facilitates water transport in plants (mention one structural feature and its role).",
    marks: "4 / 5",
    score: 4,
    maxMarks: 5,
    status: "good",
    answered: true,
    page: 2,
    answerPage: 4,
    feedback: "Lignified cell walls providing tensile strength correctly highlighted. Continuous hollow tube structure mentioned.",
    extractedAnswerText: "Xylem vessels are made of dead hollow cells with lignified walls that withstand tension without collapsing during water suction.",
    region: { x: 2, y: 4, width: 95, height: 22, page: 4 },
  },
  {
    id: "q11a",
    number: "11",
    subPart: "a.",
    body: "A diagram shows two potted plants — Plant A in bright light with broad green leaves, Plant B kept in dim light with pale, elongated leaves.",
    marks: "2 / 2",
    score: 2,
    maxMarks: 2,
    status: "good",
    answered: true,
    page: 2,
    answerPage: 4,
    feedback: "Correct deduction identifying etiolation due to lack of sunlight for chlorophyll synthesis.",
    extractedAnswerText: "Plant B shows etiolation (etiolated growth) because without sunlight, chlorophyll cannot be produced, causing yellow pale leaves and elongated stems reaching for light.",
    region: { x: 2, y: 28, width: 95, height: 24, page: 4 },
  },
  {
    id: "q11b",
    number: "11",
    subPart: "b.",
    body: "Suggest one practical measure to help Plant B recover.",
    marks: "1 / 3",
    score: 1,
    maxMarks: 3,
    status: "partial",
    answered: true,
    page: 2,
    answerPage: 4,
    feedback: "Suggesting moving to bright sunlight is partially correct, but missed mentioning gradual acclimatization to avoid sun scorch, and checking soil moisture.",
    extractedAnswerText: "Move Plant B to bright sunlight.",
    region: { x: 2, y: 54, width: 95, height: 18, page: 4 },
  },
  {
    id: "q12",
    number: "12",
    body: "A resting person has tidal volume (air per breath) of 0.5 L and breathes 12 times per minute.",
    marks: "4 / 5",
    score: 4,
    maxMarks: 5,
    status: "good",
    answered: true,
    page: 2,
    answerPage: 4,
    feedback: "Total pulmonary ventilation calculated accurately as 0.5 L × 12 = 6.0 L/min.",
    extractedAnswerText: "Minute Ventilation = Tidal Volume × Respiratory Rate = 0.5 L × 12 breaths/min = 6.0 L/min.",
    region: { x: 2, y: 74, width: 95, height: 12, page: 4 },
  },
  {
    id: "q13",
    number: "13",
    body: "If dead space is 0.15 L per breath, calculate the alveolar ventilation per minute. Show working.",
    marks: "4 / 5",
    score: 4,
    maxMarks: 5,
    status: "good",
    answered: true,
    page: 2,
    answerPage: 4,
    feedback: "Alveolar ventilation = (0.5 - 0.15) × 12 = 0.35 × 12 = 4.2 L/min. Formula and arithmetic are correct.",
    extractedAnswerText: "Alveolar Ventilation = (Tidal Volume - Dead Space) × Frequency = (0.5 L - 0.15 L) × 12 = 0.35 L × 12 = 4.2 L/min.",
    region: { x: 2, y: 87, width: 95, height: 11, page: 4 },
  },
];
